package duodev.take.eazy.utils

const val USERS = "Users"
const val ADMIN = "Admin"
const val ORDERS = "Orders"
const val CART = "Cart"
const val ITEMS = "Items"
const val STORES = "Stores"
const val STORE = "Store"
const val SERVICES = "Services"
const val CATEGORIES = "categories"
const val PICK_ITEM_IMAGE = 3
const val ALLOWED_CHARS = "0123456789qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
const val ITEM_IMAGES = "itemimages"
const val ITEM_IMAGE = "itemimage"
const val GROCERIES = "Groceries and essentials"
const val MEDICINES = "Medicines"
const val FRUITS = "Fruits and vegetables"
const val BOOKS = "Books and stationary"
const val GIFTS = "Gifts and lifestyles"
const val MEAT = "Meat and fish"
const val PET = "Pet supplies"
const val HEALTH = "Health and Energy supplements"
const val SWEETS = "Sweets"
const val ELECTRICAL = "Electrical appliances"
const val BODY_WASH = "Body wash and grooming"